const Activities = {
  f_1_1: `Our <a href="https://www.coastalstay.co.uk">pembrokeshire campsite</a> was voted as one of the top campsites in the UK for adventure activities and is a great base to visit the Pembrokeshire activities and attractions. Whether it’s adrenaline fuelled adventure activities, scenic coastal walks or rich historic towns, its got the lot.`,

  f_2_1: `The St Davids Cathedral dates back to the 12th century and has since been a popular place of pilgrimage. St David chose this beautiful region as the site of his monastery in the 6th century and you will find his shrine inside..`,
  f_2_2: `It is well worth setting aside a few hours to visit the cathedral, even if you don’t have an interest in history. There is an exhibition designed to introduce the pilgrim/visitor to the history and life of the Cathedral today including its daily worship..`,

  f_3_1: `Regarded as one of the most beautiful coastlines in the world, there is no doubt that the scenery here is stunning. Pembrokeshire has become a hotspot for walkers / hikers, and our campsite caters very well for those wanting to walk the pembrokeshire coastal national park. According the the guardian’s list of the top 10 walks in Wales, four of them are within 5 miles, with one of them right on the doorstep.`,
  f_3_2: `The routes we often recommend to our visitors is the walk from Abereiddy beach (just down the road), around the coastal path to Porthgain. The walk is roughly three miles long and has, what we believe to be, some of the most incredible views on the ocean. It offers views all the way north east to Strumble head all the way to St Davids head in the south west. The walk begins by climbing over the top of the blue lagoon. The walk ends in Porthgain which is a perfect place to grab a bite to eat or have a drink. The walk is great because there is a bus that runs from outside our <a href="https://www.coastalstay.co.uk">campsite</a> to Abereiddy, and one that stops in Porthgain, so you can get a bus to and from the start and end point of the walk.`,
  f_3_3: `Another popular walk is at Abermawr, a circular wooded walk that ends up at a pebbled beach, it’s great in the early summer as the entire wood fills with bluebells, which has led to it often being refered to as (blue-bell woods). Another (slightly longer) walk is one from Whitesands beach all the way towards St Davids head, is walk is roughly three miles out and three / four miles back, depending on whether or not you want to climb Carn Llaity, often recommended if you have the energy, because it offers incredible views of the St Davids peninsula.`,

  // Surfing
  f_4_1: `If you’re looking to do some surfing there are some great beaches available locally, most of which are features in the guardians list of <a href="http://www.theguardian.com/travel/2013/jul/19/searching-for-the-perfect-beach-pembrokeshire">perfect beaches</a> in Pembrokeshire.`,
  f_4_2: `Abereiddy is often overlooked as it requires a fair bit of swell to work properly. A very popular choice is <a href="http://www.visitpembrokeshire.com/explore-pembrokeshire/beaches/whitesands/">Whitesands</a>, which is well equipped for surfing, it has a great beach, with ample parking and a nice cafe. The beach picks up the most waves in the area and is guarded by the RNLI lifeguards.`,
  f_4_3: `A good alternative to Whitesands is Newgale, it is usually less busy and because the beach is so long (two miles), there is more chance of having a quite surf. The water temperature here in summer is warm enough to comfortably surf in a 3/2 without boots and gloves. If you are looking for more specific surfing conditions check out this guide to <a href="http://magicseaweed.com/Pembrokeshire-Surfing/12/">surfing in pembrokeshire</a>`,

  // Coasteering
  f_5_1: `Pembrokeshire is a fantastic place to coasteer, and often regarded as the birthplace of the activity, it is a blend of rock-hopping, scrambling, wave-riding, cave-exploring and cliff-jumping for the ultimate aquatic adventure. Yet en route you’ll discover wildlife and beautiful scenery too`,
  f_5_2: `Luckily for our campers our local beach, Abereiddy, is regarded as one of the best locations in the world to coasteer. There are tons of different adventure companies that offer coasteering, and we can’t really give you an oppinion on which is better than the next, which ever company you choose, you will have a day you will never forget.`,
};

export default Activities;
