const Camping = {
  f_1_1: `Our campsite provides just enough luxury to keep you comfortable and content, but not too much that you forget you’re camping in nature.`,
  f_1_2: `Weather you're staying a double bed in our bell-tent or pitched up under the stars Pembrokeshire has something for every holiday`,
  f_2_1: `We know how important campfires are to a camping trip, especially when you’ve bought along marshmallows! Not only do they offer warmth, and an atmospheric backdrop to beautiful sunset and evening games / discussions, but they also provide plenty of heat for cooking.`,
  f_2_2: `We have a large supply of locally sourced and seasoned wood available daily and a handful of movable fire pits, perfect for your own personal 
  pitch campfire. Fires are only to be lit in the provided fire pit.`,
  f_3_1: `We have five star rated bathroom facilities with a double size hot water power shower, toilet and mirror / wash hand basin. In addition to our luxury bathroom, we have a new back to basics toilet and shower block with three hot water showers and two toilets.`,
  f_3_2: `We also have washing up facilities outside for cleaning dishes and an extended garden water hose for spraying down if necessary. If you’re looking for storage we are adding a couple of lockers this year so people can lock away their valuables when they leave the campsite for the day.`,
  f_4_1: `Who doesn’t love a great picnic? So to accommodate, we’ve built large oversized picnic benches for each pitch - large enough to fit the entire family! Enjoy your food whilst overlooking a meadow of cows with the sea as a distant backdrop.`,

  f_5_1: `We are blessed to be in a part of the world where wildlife is in abundance, the Pembrokeshire National park. We also happen to be right next to a National Trust Conservation area.`,
  f_5_2: `If you’re keen on bird watching then there is plenty to see here. The field under our campsite often has young calf’s during the summer months. On the campsite we have our own resident pair of goats as well as two miniature Shetland ponies, so if you have any food to spare, the goats will be more than happy to eat your leftovers.`,
  f_6_1: `We are less than a mile from Aberiddy beach and the famous Blue Lagoon, host of the Red Bull cliff diving championships, and a mile from the popular fishing village of Porthgain, home to the award winning ‘Shed’ bistro restaurant and ‘The Sloop inn’ a family pub.`,
  f_6_2: ` As well as everything that’s just on our doorstep, we are also just a five miles from St Davids, the smallest city in Britain, with its great wealth restaurants and local shops. Also the home of the famous St Davids Cathedral a site of pilgrimage and worship for more than 800 years.`,
  f_7_1: `We were chosen by Red Bull as one of the top 10 adventure campsites. If you’ve looking for adventure then Pembrokeshire has plenty to offer. Surfing, Climbing and Kayaking just to name a few.`,
  f_7_2: `Coasteering was invented in Pembrokeshire – at least that’s where the age-old pastime of scrambling over cliffs and jumping into the sea was given its own name. It’s a fantastic day of rock-pooling adventures in the enticing natural playground that is the Pembrokeshire coastline. <a href="https://www.coastalstay.co.uk/pembrokeshire-activities">Pembrokeshire Activities.</a>`,
  f_8_1: `If you’ve come to Pembrokeshire you can’t miss an opportunity to walk on the Coastal National Park. The coastal path stretches the entire length of Wales, but we are lucky enough to have one of the best section right on our doorstep.`,
  f_8_2: `The walk from Abereiddy to Porthgain is recognised as one of the best, as mentioned here in the guardian: <a href="http://www.theguardian.com/travel/2013/jul/19/searching-for-the-perfect-beach-pembrokeshire">Best UK Walks</a>. If your looking for cycles routes, there are rides to suit all ages, whether it be Mountain Biking, Touring or tearing up the roads on a Racing Bike.`,
  f_9_1: `A frequent bus service stops directly outside the campsite and runs to and from St Davids, Fishguard and Haverfordwest. This makes it the ideal base for walkers and hikers of the Pembrokeshire Coastal National Paths.`,
  f_9_2: `Onsite we have a small cafe open in the morning for breakfast and late afternoon for cream teas. We can even bring you breakfast to your tent! We will stock essentials like milk, eggs, logs, mallets, windbreakers and spare tent pegs. Also make the most of our herb garden to give that extra kick to your campfire dishes!`,
  f_10_1: `Children and pets are more than welcome, we have onsite pets including a dog, kittens, goat and a pair of miniature horses, so the dog must be obedient and kept on a lead to avoid disrupting other campers. Care must be taken with younger children around the lake.`,
  f_10_2: `If you are looking for a hi-tech holiday park then we are probably not for you, but if you want your children to know how to build a den or forage for blackberries then we probably are.`,
  f_11_1: `An ideal and tranquil base for viewing the attractions of Pembrokeshire, yet only one a few miles from the shops, pubs and restaurants of St Davids.`,
  f_11_2: `If this sounds like a campsite you’d be interested in, check out our <a href="https://www.coastalstay.co.uk/pricing">camping prices</a> or get in touch.`,
  f_12_1: `A few years back we added our own wood fired pizza oven so we could make food for friends and family - then we opened ocassionally to give pizza to campers...it went so well our pizza oven is now open every evening during the high season for take away`,
  f_13: `If you're looking for a twist of luxury, take a look at our fully catered <a href="https://www.coastalstay.co.uk/glamping-pembrokeshire">glamping bell tent</a>. They are furnished with everything you need, double bed, cooking equipment, towels and we can even bring coffee to you in bed in the morning.`,
};

export default Camping;
