const Glamping = {
  f_1_1: `Open up the canvas in the morning and get back into your comfortable bed whilst you watch the sun light up the Pembrokeshire Coast. Our traditional bell tents offer a unique “wild glamping” holiday experience in Pembrokeshire, comfortable and hassle free, allowing you to fully enjoy the camping experience.`,
  f_1_2: `Our traditional canvas bell tents, with lovely fittings, are thoughtfully decorated with coconut matted floor, covered with rugs and lights twinkle around the tent creating a lovely ambience.`,
  f_2_1: `Bell tent glamping is the most popular form of glamping, and it’s easy to see why; traditional camping under canvas with a twist of luxury and glamour.`,
  f_2_2: `Our bell tents use traditional cotton canvas, meaning you will experience a completely unique camping experience as opposed to nylon tents, meaning they are cool in the day and warm and well ventilated at night.`,
  f_3_1: `A bell tent trip provides the real camping experience made easy, with just about all the camping equipment you should need, all set-up and waiting for you to arrive.`,
  f_3_2: `Our tents come pre-erected and fully furnished. They include electric, a comfortable double bed with bedding, gas cooker, cooking equipment, tableware (not forgetting the all-important bottle-opener!) , picnic table and firepit. We also provide kindling and logs for your first nights fire. [additional logs can be purchased from receiption]`,
  f_4_1: `Our luxury bathroom was once used for Bed & Breakfast, and had an official five star rating, now it is reserved for our campers. We also have a more back to basic toilet & shower block that many people prefer for it’s unique character and charm.`,
  f_4_2: `We have an outside washing up area and warm water to clean up those dishes after last nights BBQ. There is also a fridge available if you wish to keep some of your items cool.`,
  f_5_1: `We are blessed to be in a part of the world where wildlife is in abundance, the Pembrokeshire National park. We also happen to be right next to a National Trust Conservation area`,
  f_5_2: `If you’re keen on bird watching then there is plenty to see here. The field under our campsite often has young calfs during the summer months. On the campsite we have our own resident pair of goats as well as two miniature shetland ponies, so if you have any food to spare, the goats will be more than happy to eat your leftovers.`,
  f_6_1: `We are less than a mile from Aberiddy beach and the famous Blue Lagoon, host of the Red Bull cliff diving championships, and a mile from the popular fishing village of Porthgain, home to the award winning ‘Shed’ bistro restaurant and ‘The Sloop inn’ a family pub.`,
  f_6_2: `As well as everything that’s just on our doorstep, we are also just a five miles from St Davids, the smallest city in Britain, with its great wealth restaurants and local shops. Also the home of the famous St Davids Cathedral a site of pilgrimage and worship for more than 800 years.`,
  f_7_1: `If you’ve looking for adventure then Pembrokeshire has plenty to offer. Surfing, Climbing and Kayaking just to name a few.`,
  f_7_2: `Coasteering was invented in Pembrokeshire – at least that’s where the age-old pastime of scrambling over cliffs and jumping into the sea was given its own name. It’s a fantastic day of rockpooling adventures in the enticing natural playground that is the Pembrokeshire coastline. See more Pembrokeshire Activities.`,
  f_8_1: `
If you’ve come to Pembrokeshire you can’t miss an opportunity to walk on the Coastal National Park. The coastal path stretches the entire length of Wales, but we are lucky enough to have one of the best section right on our doorstep.`,
  f_8_2: `The walk from Abereiddy to Porthgain is recognised as one of the best, as mentioned here in the guardian: Best UK Walks. If your looking for cycles routes, there are rides to suit all ages, whether it be Mountain Biking, Touring or tearing up the roads on a Racing Bike.`,
  f_9_1: `A frequent bus service stops directly outside the campsite and runs to and from St Davids, Fishguard and Haverfordwest. This makes it the ideal base for walkers and hikers of the Pembrokeshire Coastal National Paths.`,
  f_9_2: `Onsite we have a small cafe open in the morning for breakfast and evening pizza. We can even bring you breakfast to your tent! Also make the most of our herb garden to give that extra kick to your campfire dishes!`,
  f_10_1: `If you are looking for a back to basic camping experience with a twist of luxury and all the hassle removed, then a visit to the Pembrokeshire National Park, and our bell tent may be right just the cup of tea.`,
  f_10_2: `Remove all the stress of camping and carting all your equipment and let us take care of all that. Instead, spend your time enjoying Pembrokeshire and all the beauty it has to offer.`,
  f_10_3: `If this sounds like a campsite you’d be interested in, check out our camping prices or get in touch.`,
  f_11_1: ``,
  f_11_2: ``,
  f_12_1: ``,
  f_13: ``,
};

export default Glamping;
